[build]
target = "riscv32imc-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Texamples/device.x",
]

# [target.riscv32imc-unknown-none-elf]
# rustflags = [
#   "-C", "link-arg=-Texamples/device.x",
# ]
